networks:
  docker_net:
    external: true

services:
  postgres-test:
    image: postgres:16-alpine
    hostname: postgres-test
    container_name: postgres-test
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
    ports:
      - "6543:5432"
    networks:
      - docker_net